sudo: required

services:
  - docker

env:
  - IMAGE_NAME=openpose

before_install:
  - docker build -t $DOCKER_USERNAME/$IMAGE_NAME .
  - docker images

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/$IMAGE_NAME
